<?php

/**
 * @file
 * Administrative interface to seed. Without this module, you cannot create or edit your seeds.
 */


/**
 * Implements hook_help().
 */
function seed_ui_help($path, $arg) {
  switch ( $path ) {
    case 'admin/structure/seed':
      return '<p>' . t('Seeds are for adding an instant win functionality to your system. They are grouped by taxomony terms from the Seed vocabulary.') . '</p>';
  }
}

/**
 * Implements hook_menu().
 */
function seed_ui_menu() {
  $items['admin/structure/seed'] = array(
    'title' => 'Seeds',
    'description' => 'Manage seeds.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('seed_ui_overview_terms'),
    'access arguments' => array('administer seeds'),
    'file' => 'seed_ui.admin.inc',
  );
  $items['admin/structure/seed/%taxonomy_term'] = array(
    'title' => 'Seeds',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('seed_ui_overview_seeds', 3),
    'access arguments' => array('administer seeds'),
    'file' => 'seed_ui.admin.inc',
  );
  $items['admin/structure/seed/%taxonomy_term/add'] = array(
    'title' => 'Add seed',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('seed_ui_form_seed', array(), 3),
    'access arguments' => array('administer seeds'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'seed_ui.admin.inc',
  );

  $items['seed/%seed'] = array(
    'title' => 'Seed',
    'title callback' => 'seed_ui_title',
    'title arguments' => array(1),
    'page callback' => 'seed_ui_page',
    'page arguments' => array(1),
    'access arguments' => array('administer seeds'),
    'file' => 'seed_ui.admin.inc',
  );
  $items['seed/%seed/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['seed/%seed/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('seed_ui_form_seed', 1, NULL),
    'access arguments' => array('administer seeds'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'seed_ui.admin.inc',
  );
  
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function seed_ui_admin_paths() {
  return array(
    'seed/*/edit' => TRUE,
  );
}

/**
 * Implements hook_theme().
 */
function seed_ui_theme() {
  return array(
    'seed_ui_overview_terms' => array(
      'render element' => 'form',
    ),
    'seed_ui_overview_seeds' => array(
      'render element' => 'form',
    ),
  );
}